apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: app
    image: public.ecr.aws/docker/library/centos:latest
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"        
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
    securityContext:
      allowPrivilegeEscalation: false  
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL  
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim