apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: test  
spec:
  containers:
  - name: demo
    image: nginx:1.22.1  
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: true        

    
