apiVersion: v1
kind: Service
metadata:
  name: "service-demo-nginx"
  namespace: "demo"
  annotations:
   service.kubernetes.io/topology-aware-hints: auto
spec:
  # type:
  ports:
    - port: 80
      targetPort: 80
      port: 80
  selector:
    app: "demo-nginx"
